import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { api } from "../utils/api";

const BuildingsPage: NextPage = () => {
  const buildings = api.buildings.getBuildings.useQuery();

  return (
    <>
      <Head>
        <title>Buildings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Buildings</h1>
        <Link href='/'>Home</Link>

        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Energy Grade</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {buildings.data?.map(building => (
              <tr key={building.id}>
                <td>{building.id}</td>
                <td>{building.energyGrade}</td>
                <td>{building.description}</td>
              </tr>
            ))}
          </tbody>
        </table>


      </main>
    </>
  );
};

export default BuildingsPage;
